### ISSUE TITLE
Using request_creation_time as record timestamp, and additional custom parsing

### ISSUE THREAD

**Issue by davidk81** [newrelic/aws_s3_log_ingestion_lambda#26]
1. We would like to use `request_creation_time` as the timestamp when ingested into New Relic (versus default which is using the time-of-ingest). Is it possible to add custom parsing to the lamba to enable this? 

I see there might be potential to parse the data here:
https://github.com/newrelic/aws_s3_log_ingestion_lambda/blob/master/src/handler.py#L112-L126

2. The second question is, are we able to parse and add additional fields. Our use-case is we would like to add additional filtering on the uri path (eg: filter out some uri params such as `https://hello.com/user/1234`). Such filtering may be difficult or impossible to do using glob patterns with the NR server-side parsing

**Comment by danybmx** [comment]
Hi @davidk81, 

I can't found the `request_creation_time` in the lambda S3 event nor in the lambda context that is received by the handler. Although there is an `eventTime` for S3 events. Does that help?

The second point is related to #43 (#33 originally) that will be merged soon.

**Comment by davidk81** [comment]
thanks @danybmx, thanks for getting back to us. we will take another look into this when we have time. i will close this issue for now.
