### ISSUE TITLE
Support parsing timestamp and add it to log event when log message is formatted as JSON.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/aws_s3_log_ingestion_lambda#27]
I wonder it's related to #26.

When a log file contains one line JSON and JSON has a timestamp value, how about parsing timestamp and add it to a Log event timestamp?

```
{"timestamp": 1622622938, "key1": "value1", "key2": "value"}
{"timestamp": 1622622948, "key1": "valueA", "key2": "valueB"}
```

At this point, the handler doesn't parse anything so the log event timestamp will be a time when logs are sent to New Relic Logs.

https://github.com/newrelic/aws_s3_log_ingestion_lambda/blob/master/src/handler.py#L112-L126

**Comment by danybmx** [comment]
Hi!

New Relic does that job in the logs pipeline, so we don't need to take care of this in the lambda. I've just tested it right now to ensure that feature work for s3 logs and it worked as expected.
If the pipeline found a log with a timestamp field, that timestamp will be used (if it's a valid one).

Those are the logs used for doing the test:
```
{"timestamp": 1661454898000, "message": "A log message generated in the generate-log-file-and-upload for s3 lambda testing", "level": "DEBUG", "statusCode": 400}
{"timestamp": 1661454898100, "message": "A log message generated in the generate-log-file-and-upload for s3 lambda testing", "level": "TRACE", "statusCode": 100}
{"timestamp": 1661454898200, "message": "A log message generated in the generate-log-file-and-upload for s3 lambda testing", "level": "TRACE", "statusCode": 204}
```

Also, one detail to bear in mind is that the log api drop messages older than 2 days, so if you are going to test this, ensure you have recent timestamps.

Closing this issue, regards!
