### ISSUE TITLE
Support CloudTrail logs

### ISSUE THREAD

**Issue by msummers-nr** [newrelic/aws_s3_log_ingestion_lambda#28]
CloudTrail's JSON payload begins with an array of Records, the current lambda places all Records into a single NR Log entry.

The ask it to detect CloudTrail as a source and generate one NR Log entry for each CloudTrail Records entry.

**Comment by danybmx** [comment]
Hi, this was merge #29 and published on version 1.1.2. Thanks @msummers-nr
